const { withProjectBuildGradle, withPodfile } = require('@expo/config-plugins');

// Android: inject ffmpegKitPackage into ROOT build.gradle ext block
const withFFmpegKitAndroid = (config) => {
  return withProjectBuildGradle(config, (cfg) => {
    const gradle = cfg.modResults.contents;
    if (!gradle.includes('ffmpegKitPackage')) {
      if (gradle.includes('ext {')) {
        cfg.modResults.contents = gradle.replace(
          /ext\s*\{/,
          `ext {\n        ffmpegKitPackage = "full-gpl"`
        );
      } else {
        cfg.modResults.contents = gradle.replace(
          /^(allprojects|buildscript)/m,
          `ext {\n    ffmpegKitPackage = "full-gpl"\n}\n\n$1`
        );
      }
    }
    return cfg;
  });
};

// iOS: patch Podfile to use ffmpeg-rn subspec (full-gpl)
// This replaces the autolinking entry with a subspec-specific pod declaration
const withFFmpegKitIos = (config) => {
  config = withPodfile(config, (cfg) => {
    let contents = cfg.modResults.contents;

    // Remove the autogenerated ffmpeg-kit-react-native pod line from autolinking
    contents = contents.replace(
      /# @generated begin ffmpeg-kit-react-native-import[\s\S]*?# @generated end ffmpeg-kit-react-native-import\n?/m,
      ''
    );

    // Add the subspec version before the target block if not already present
    if (!contents.includes('ffmpeg-kit-react-native')) {
      contents = contents.replace(
        /^(target\s+['"].*['"]\s+do)/m,
        `$1\n  pod 'ffmpeg-kit-react-native', :subspecs => ['full-gpl'], :podspec => '../node_modules/ffmpeg-kit-react-native/ffmpeg-kit-react-native.podspec'`
      );
    }

    cfg.modResults.contents = contents;
    return cfg;
  });

  return config;
};

module.exports = (config) => {
  config = withFFmpegKitAndroid(config);
  config = withFFmpegKitIos(config);
  return config;
};
