const { withAppBuildGradle, withProjectBuildGradle, withPodfile, withDangerousMod } = require('@expo/config-plugins');
const fs = require('fs');
const path = require('path');

// Android: inject ffmpegKitPackage into ROOT build.gradle ext block
const withFFmpegKitAndroid = (config) => {
  return withProjectBuildGradle(config, (cfg) => {
    const gradle = cfg.modResults.contents;
    if (!gradle.includes('ffmpegKitPackage')) {
      // inject into ext block if exists, otherwise add one
      if (gradle.includes('ext {')) {
        cfg.modResults.contents = gradle.replace(
          /ext\s*\{/,
          `ext {\n        ffmpegKitPackage = "video"`
        );
      } else {
        cfg.modResults.contents = gradle.replace(
          /^(allprojects|buildscript)/m,
          `ext {\n    ffmpegKitPackage = "video"\n}\n\n$1`
        );
      }
    }
    return cfg;
  });
};

// iOS: copy podspec + patch Podfile
const withFFmpegKitIos = (config) => {
  config = withDangerousMod(config, [
    'ios',
    async (cfg) => {
      const iosDir = cfg.modRequest.platformProjectRoot;
      const src = path.join(__dirname, '..', 'ios', 'ffmpeg-kit-ios-full-gpl.podspec');
      const dest = path.join(iosDir, 'ffmpeg-kit-ios-full-gpl.podspec');
      if (fs.existsSync(src)) {
        fs.copyFileSync(src, dest);
      }
      return cfg;
    },
  ]);

  config = withPodfile(config, (cfg) => {
    let contents = cfg.modResults.contents;

    // Remove the broken autogenerated ffmpeg-kit-react-native pod line
    contents = contents.replace(
      /# @generated begin ffmpeg-kit-react-native-import[\s\S]*?# @generated end ffmpeg-kit-react-native-import\n?/m,
      ''
    );

    if (!contents.includes('ffmpeg-kit-ios-full-gpl')) {
      contents = contents.replace(
        /^(target\s+['"].*['"]\s+do)/m,
        `$1\n  pod 'ffmpeg-kit-ios-full-gpl', :podspec => './ffmpeg-kit-ios-full-gpl.podspec'`
      );
    }

    cfg.modResults.contents = contents;
    return cfg;
  });

  return config;
};

module.exports = (config) => {
  config = withFFmpegKitAndroid(config);
  config = withFFmpegKitIos(config);
  return config;
};
